name: Test Container SSH
version: "1.2.0"
slug: test-container
description: Test Container SSH
url: "https://github.com/testmail123456/test-container-ssh"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - type: data
    read_only: false
startup: services
ports:
  8000/tcp: 8000
full_access: true
apparmor: false
udev: true
devicetree: true
